# Generated by Django 5.2.4 on 2025-09-19 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Pagamento',
                'verbose_name_plural': 'Tipos de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(unique=True)),
                ('order_id', models.IntegerField(unique=True)),
                ('order_date', models.DateTimeField()),
                ('shipping_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_orders', to='customer.customer')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_orders', to='buy_order.paymenttype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_orders', to='buy_order.status')),
            ],
            options={
                'verbose_name': 'Ordem de Compra',
                'verbose_name_plural': 'Ordens de Compra',
            },
        ),
        migrations.CreateModel(
            name='EcsBuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecs_order_id', models.CharField(max_length=50)),
                ('ecs_order_number', models.CharField(max_length=50)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('coupon', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline_days', models.PositiveIntegerField()),
                ('ecs_carrier', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_zip_code', models.CharField(max_length=8)),
                ('recipient_city', models.CharField(max_length=100)),
                ('recipient_state', models.CharField(max_length=2)),
                ('ecs_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecs_buy_orders', to='buy_order.buyorder')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecs_buy_orders', to='company.company')),
            ],
            options={
                'verbose_name': 'Ecs - Ordem de Compra',
                'verbose_name_plural': 'Ecs - Ordens de Compra',
            },
        ),
    ]
