# Generated by Django 5.2.4 on 2025-09-18 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_order', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_orders', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_orders', to='buy_order.paymenttype'),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_orders', to='buy_order.status'),
        ),
    ]
